### ISSUE TITLE
Failed parsing mandrill error, as far as I can tell

### ISSUE THREAD

**Issue by RanGold** [rschreijer/lutung#61] opened 2015-09-30 09:27 UTC
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:768)
	at com.google.gson.Gson.fromJson(Gson.java:717)
	at com.google.gson.Gson.fromJson(Gson.java:689)
	at com.microtripit.mandrillapp.lutung.model.MandrillRequestDispatcher.execute(MandrillRequestDispatcher.java:62)
	at com.microtripit.mandrillapp.lutung.controller.MandrillUtil.query(MandrillUtil.java:45)
	at com.microtripit.mandrillapp.lutung.controller.MandrillMessagesApi.sendTemplate(MandrillMessagesApi.java:211)
	at com.microtripit.mandrillapp.lutung.controller.MandrillMessagesApi.sendTemplate(MandrillMessagesApi.java:138)
```

**Comment by RanGold** [comment] 2015-09-30 09:28
```
<dependency>
            <groupId>com.mandrillapp.wrapper.lutung</groupId>
            <artifactId>lutung</artifactId>
            <version>0.0.4</version>
        </dependency>
```

**Comment by billoneil** [comment] 2015-11-15 01:59
Dupe of https://github.com/rschreijer/lutung/issues/25

**Closed by billoneil** 2015-11-15 01:59 UTC
